# Generated by Django 4.2.3 on 2023-07-10 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listing_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="active",
            new_name="is_active",
        ),
    ]
