# Generated by Django 4.2.3 on 2023-07-11 21:58

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_rename_active_listing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=auctions.models.path_and_rename
            ),
        ),
    ]
