# Generated by Django 4.2.3 on 2023-07-16 16:31

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_listing_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
