# Generated by Django 4.2.3 on 2023-07-21 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_listing_bids_alter_listing_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="bids",
        ),
    ]
