# Generated by Django 4.2.3 on 2023-07-24 13:11

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_alter_comment_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
