# Generated by Django 4.2.3 on 2023-07-27 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0018_alter_comment_options_alter_listing_watchlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["-created_at"]},
        ),
    ]
